# Docker compose file for CICD homelab:

version: '3.7'
services:
########################################################################################################
#                                          Moniotoring
########################################################################################################
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes: 
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 9001:9000
    restart: unless-stopped
########################################################################################################
#                                      Static Code Analysis
########################################################################################################
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube1_data:/opt/sonarqube/data
      - sonarqube1_extensions:/opt/sonarqube/extensions
      - sonarqube1_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql1:/var/lib/postgresql
      - postgresql1_data:/var/lib/postgresql/data
########################################################################################################
#                                      Continuous Build/Deploy
########################################################################################################
  jenkins:
    image: ${JENKINS_IMAGE}:${JENKINS_IMAGE_VER}
    container_name: jenkins
    privileged: true
    user: 'root'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    ports:
      - '2200:22' 
    # expose:
    #   - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${PUBKEY}
volumes:
  portainer_data:
    driver: local
  jenkins_data:
    driver: local
  sonarqube1_data:
    driver: local
  sonarqube1_extensions:
    driver: local
  sonarqube1_logs:
    driver: local
  postgresql1:
    driver: local
  postgresql1_data:
    driver: local


    #TO do:
    # 1. fix agent ssh connection <--> jenkins
    # http://0.0.0.0:8080/computer/jenkins%5Fagent1/configure
    # https://stackoverflow.com/questions/37331571/how-to-setup-ssh-keys-for-jenkins-to-publish-via-ssh
    # https://dev.to/ashiqursuperfly/jenkins-controller-agent-master-slave-setup-in-10-minutes-using-docker-2a78
    # https://github.com/jenkinsci/docker-ssh-agent

    # 2. sonarqube project setup
